CREATE INDEX IF NOT EXISTS "activities_occurred_idx" ON "activities" USING btree ("occurred_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "estimates_customer_idx" ON "estimates" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "estimates_lead_idx" ON "estimates" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "expenses_customer_idx" ON "expenses" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "expenses_project_idx" ON "expenses" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invoices_customer_idx" ON "invoices" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invoices_quote_idx" ON "invoices" USING btree ("quote_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invoices_project_idx" ON "invoices" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invoices_credit_for_idx" ON "invoices" USING btree ("credit_for_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invoices_status_due_idx" ON "invoices" USING btree ("status","due_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invoices_issue_date_idx" ON "invoices" USING btree ("issue_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leads_status_idx" ON "leads" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leads_customer_idx" ON "leads" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leads_follow_up_idx" ON "leads" USING btree ("follow_up_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_tasks_open_idx" ON "project_tasks" USING btree ("done","due_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "projects_customer_idx" ON "projects" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "projects_status_idx" ON "projects" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "projects_quote_idx" ON "projects" USING btree ("quote_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "projects_lead_idx" ON "projects" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quotes_customer_idx" ON "quotes" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quotes_lead_idx" ON "quotes" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quotes_project_idx" ON "quotes" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quotes_issue_date_idx" ON "quotes" USING btree ("issue_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscriptions_project_idx" ON "subscriptions" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscriptions_quote_idx" ON "subscriptions" USING btree ("quote_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscriptions_last_invoice_idx" ON "subscriptions" USING btree ("last_invoice_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "time_entries_invoice_idx" ON "time_entries" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "time_entries_date_idx" ON "time_entries" USING btree ("date");