import type { MetadataRoute } from "next";

// Icons are generated by scripts/build-icons.mjs from public/logo-mark.svg.
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/de",
    name: "Webnova: Webdesign Agentur für Schweizer Unternehmen",
    short_name: "Webnova",
    description: "Webseite erstellen lassen: Webdesign, Redesign, Wartung und SEO für Unternehmen in der ganzen Schweiz.",
    start_url: "/de",
    scope: "/",
    display: "standalone",
    lang: "de-CH",
    background_color: "#ffffff",
    theme_color: "#24405a",
    categories: ["business", "productivity"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
