import type { MetadataRoute } from "next";

// Icons are generated by scripts/build-icons.mjs from public/logo-mark.svg.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Webnova: Webdesign, Onlineshops und SEO für KMU",
    short_name: "Webnova",
    description: "Webseiten, Onlineshops, SEO und Kassensysteme für Schweizer KMU.",
    start_url: "/de",
    scope: "/",
    display: "standalone",
    lang: "de-CH",
    background_color: "#ffffff",
    theme_color: "#24405a",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
